### ISSUE TITLE
support external  Tree element drag and drop from tow ngx-nestable Trees

### ISSUE THREAD

**Issue by mcbenjemaa** [cybercomet/ngx-nestable#7]
i have a component to implement, and i use this library and it's okay for me, i'm very satisfied.
but i have more features to integrate with this library .
let's assume i have tow Trees, and i want to accept drag from one to another, how to achieve that ?
i have an app that is developed with AngularJS, now i am migrating to Angular 6.
any help from the authors !
- the old way is integrated with https://github.com/angular-ui-tree/angular-ui-tree
- please check the screenshot.

![drag](https://user-images.githubusercontent.com/15221272/48257105-e60d2c00-e411-11e8-9b38-3aef2b33740c.PNG)

**Comment by Jbrownstone** [comment]
Hello, i'd like to achieve the same behavior as the one your describing, i was wondering if you found a workaround with this library?

Also why aren't you using the librairy that you linked as it allows to do exactly what you want to achieve?

Cheers.

**Comment by medmedchiheb** [comment]
Hi,

i didn't find a solution with this library,
and i tried using this library, https://github.com/500tech/angular-tree-component

it worked for me, since it had a great docs.

**Comment by Jbrownstone** [comment]
Alright, thanks for the tip.

**Comment by webcat12345** [comment]
This feature could be helpful.
